---
development:
  cloud_name: djjrcgwc6
  api_key: '641522855563158'
  api_secret: MNJwI5Z0gwesf3q4X9DESpkLGoI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: djjrcgwc6
  api_key: '641522855563158'
  api_secret: MNJwI5Z0gwesf3q4X9DESpkLGoI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: djjrcgwc6
  api_key: '641522855563158'
  api_secret: MNJwI5Z0gwesf3q4X9DESpkLGoI
  enhance_image_tag: true
  static_image_support: false
